// Code generated by cmd/aolib-gen from aolib-meta. DO NOT EDIT.

package packet

// Offset is Integer (x, y) screen-coordinate pair carried in MS offset / paired_offset slots.
type Offset struct {
	X int `json:"x"`
	Y int `json:"y"`
}

